apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "Nginx backend deployed"
  name: backend-deployment
  labels:
    app: backend
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: python:3.6-alpine
        command: ['sh', '-c', 'echo backend-container-index > index.html && python -m http.server 80']
        ports:
          - containerPort: 80
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "Lanzando fontend"
  name: frontend-deployment
  labels:
    app: frontend
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-proxy
        image: jorgealemangonzalez/101-todo-app
        ports:
          - containerPort: 5000
        env:
          - name: PROXY_TO_URL
            value: http://backend-service:8888
      dnsConfig:
        options:
          - name: ndots
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5000
---
