apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "Lanzando en puerto 9376"
  name: nodeport-example-deployment
  labels:
    app: nodeport-example
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: nodeport-example
  template:
    metadata:
      labels:
        app: nodeport-example
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-example-service1
  labels:
    app: nodeport-example
spec:
  type: NodePort
  selector:
    app: nodeport-example
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80