apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    app: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max-limits
  namespace: prod
spec:
  limits:
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 100Mi
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  namespace: prod
  name: podtest3
  labels:
    app: backend
    env: prod
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    resources:
      limits:
        memory: 50M
        cpu: 50m
      requests:
        memory: 40M
        cpu: 20m
