apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    kubernetes.io/change-cause: "Nuevo cambio a puerto 110"
  name: nginx-deployment
  labels:
    app: front
spec:
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 110
