---
apiVersion: v1
kind: Pod
metadata: 
  name: test
  labels:
    app: backend
    env: dev
spec:
  containers: 
  - name: cont1
    image: nginx:alpine
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 1.2.3.4